### ISSUE TITLE
Cannot run a simple Uninstall, need RunAsAdministrator

### ISSUE THREAD

**Issue by rauljunc** [deadlydog/AzureDevOps.WindowsScheduledTasks#10]
Hello I was trying to run a task scheduler uninstall, but when it runs, it throws an exception. Please see below the logs.

> 2020-04-01T06:26:37.3663261Z ##[debug]Importing module 'C:\azagent\A3\_work\_tasks\UninstallWindowsScheduledTask_cdfb7f40-dbb3-128f-9a8d-1934ee9a7748\2.0.8\Code\Shared\UserInputToWinRmSettingsMapper.psm1'.
> 2020-04-01T06:26:37.3666178Z ##[debug]Loading module from path 'C:\azagent\A3\_work\_tasks\UninstallWindowsScheduledTask_cdfb7f40-dbb3-128f-9a8d-1934ee9a7748\2.0.8\Code\Shared\UserInputToWinRmSettingsMapper.psm1'.
> 2020-04-01T06:26:37.3674461Z ##[debug]Exporting function 'Get-ComputersToConnectToOrNull'.
> 2020-04-01T06:26:37.3675429Z ##[debug]Exporting function 'Convert-UsernameAndPasswordToCredentialsOrNull'.
> 2020-04-01T06:26:37.3676558Z ##[debug]Exporting function 'Get-WinRmSettings'.
> 2020-04-01T06:26:37.3677218Z ##[debug]Importing function 'Convert-UsernameAndPasswordToCredentialsOrNull'.
> 2020-04-01T06:26:37.3677847Z ##[debug]Importing function 'Get-ComputersToConnectToOrNull'.
> 2020-04-01T06:26:37.3680819Z ##[debug]Importing function 'Get-WinRmSettings'.
> 2020-04-01T06:26:37.3681628Z ##[debug]Importing module 'C:\azagent\A3\_work\_tasks\UninstallWindowsScheduledTask_cdfb7f40-dbb3-128f-9a8d-1934ee9a7748\2.0.8\Code\Uninstall-WindowsScheduledTask.psm1'.
> 2020-04-01T06:26:37.3684915Z ##[debug]Loading module from path 'C:\azagent\A3\_work\_tasks\UninstallWindowsScheduledTask_cdfb7f40-dbb3-128f-9a8d-1934ee9a7748\2.0.8\Code\Uninstall-WindowsScheduledTask.psm1'.
> 2020-04-01T06:26:37.3741718Z ##[error]System.Management.Automation.ParentContainsErrorRecordException: At C:\azagent\A3\_work\_tasks\UninstallWindowsScheduledTask_cdfb7f40-dbb3-128f-9a8d-1934ee9a7748\2.0.8\Code\Uninstall-WindowsScheduledTask.psm1:2 char:11
> 2020-04-01T06:26:37.3744363Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.ParentContainsErrorRecordException: At C:\azagent\A3\_work\_tasks\UninstallWindowsScheduledTask_cdfb7f40-dbb3-128f-9a8d-1934ee9a7748\2.0.8\Code\Uninstall-WindowsScheduledTask.psm1:2 char:11
> 2020-04-01T06:26:37.3745161Z + #Requires -RunAsAdministrator
> 2020-04-01T06:26:37.3745390Z +           ~~~~~~~~~~~~~~~~~~~
> 2020-04-01T06:26:37.3745635Z Parameter RunAsAdministrator requires an argument.
> 2020-04-01T06:26:37.3745812Z 
> 2020-04-01T06:26:37.3745905Z 
> 2020-04-01T06:26:37.3747363Z ##[error]System.IO.FileNotFoundException: The specified module 'C:\azagent\A3\_work\_tasks\UninstallWindowsScheduledTask_cdfb7f40-dbb3-128f-9a8d-1934ee9a7748\2.0.8\Code\Uninstall-WindowsScheduledTask.psm1' was not loaded because no valid module file was found in any module directory.
> 2020-04-01T06:26:37.3749496Z ##[debug]Processed: ##vso[task.logissue type=error;]System.IO.FileNotFoundException: The specified module 'C:\azagent\A3\_work\_tasks\UninstallWindowsScheduledTask_cdfb7f40-dbb3-128f-9a8d-1934ee9a7748\2.0.8\Code\Uninstall-WindowsScheduledTask.psm1' was not loaded because no valid module file was found in any module directory.
> 2020-04-01T06:26:37.3755365Z ##[debug]Will attempt to uninstall Windows Scheduled Task 'Start QReader' on ''.
> 2020-04-01T06:26:37.5724611Z ##[error]System.Management.Automation.CommandNotFoundException: The term 'Uninstall-WindowsScheduledTask' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> 2020-04-01T06:26:37.5727373Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.CommandNotFoundException: The term 'Uninstall-WindowsScheduledTask' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> 2020-04-01T06:26:37.5728659Z    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
> 2020-04-01T06:26:37.5729426Z    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
> 2020-04-01T06:26:37.5729960Z    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
> 2020-04-01T06:26:37.5730609Z    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
> 2020-04-01T06:26:37.5731526Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
> 2020-04-01T06:26:37.5732215Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
> 2020-04-01T06:26:37.5732689Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> 2020-04-01T06:26:37.5827797Z ##[error]PowerShell script completed with 3 errors.
> 2020-04-01T06:26:37.5837076Z ##[section]Finishing: Uninstall Windows Scheduled Task 'Start QReader'

This is the configuration that I've done I have not put anything in the Server settings because I want the task scheduler to be uninstall from where this agent is ran from (Deployment Group)

> ![image](https://user-images.githubusercontent.com/50243005/78113505-bdffdd80-73f7-11ea-80b3-a1dad94565f6.png)

**Comment by deadlydog** [comment]
Hmmmm, that's odd @rauljunc . It looks like you're using a deployment group job, so I assume that means the Azure DevOps agent is running on one of your on-premise machines? Can you confirm what version of Windows is installed on the computer and what version of PowerShell it is running?

To get the PowerShell version you can run this command from a PowerShell command prompt.

```powershell
$PSVersionTable.PSVersion
```

From the logs it looks like it doesn't know what `#Requires -RunAsAdministrator` is, which [was introduced in PowerShell 4](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-7#-runasadministrator), so I'm guessing you don't have at least that version of PowerShell installed on your build agent computer.

I can look at adding a change to specify a minimum version of PowerShell 4 so that it gives a better error message.

Can you confirm that is the problem for you? Thanks!

**Comment by rauljunc** [comment]
Hello @deadlydog, I have Windows Server 2012 Standard 64-bit running on our servers, and the version of the PowerShell is 3. Would it be possible to get a backward compatibility version of this task? It would be hard to update the PowerShell version to 4 to all of our servers and also updating might make us run into other issues on our live system.

**Comment by deadlydog** [comment]
Hmmm, yeah, I believe the only thing that requires PowerShell v4 is that statement. I'll look at removing it and doing the "run as admin" check some other way.

**Comment by deadlydog** [comment]
Alright, I've made the extension PowerShell v3 compatible, but discovered that my CI/CD pipeline is broken due to what seems to be a bug in an MS task. I've opened a GitHub issue for them to investigate: https://github.com/microsoft/azure-devops-extension-tasks/issues/163

Once they fix that up I'll get a new version published.

**Comment by deadlydog** [comment]
Actually, I decided that this was a fairly safe change to make, I've merged the change into the `master` branch and manually uploaded a new v2.0.10 version of the extension to the marketplace. Give it a try and let me know how it goes. Thanks!

**Comment by rauljunc** [comment]
After further investigation, I found out that on our production environment we have PowerShell v4, so we won't need to update production, we only updated our testing environment from PowerShell v3 to PowerShell v4. The tool works great, thank you for your help.
