### ISSUE TITLE
Previous Versions

### ISSUE THREAD

**Issue by Sacrilege** [deadlydog/AzureDevOps.WindowsScheduledTasks#14]
We're using this in an on-prem TFS 2018 server. Someone deleted the extension thinking it wasn't being used. When it was realized it was being used I added it back from the marketplace. However, the version there has had the categories changed and it can no longer be used in our release definitions because of that. Any chance I can get a copy of a published version prior to that change?

**Comment by deadlydog** [comment]
Hmmm, I'm not sure what change you are referring to. You can maybe check out [the Change Log](https://github.com/deadlydog/AzureDevOps.WindowsScheduledTasks/blob/master/docs/ChangeLog.md) to pinpoint which one you're talking about.

There's also a Task Version switcher directly in the task; perhaps switching from v2 back to v1 or v0 will accomplish what you need?
![image](https://user-images.githubusercontent.com/1187140/86181362-1aec5c00-baeb-11ea-97ad-5e9b1771d267.png)

I've never "removed" functionality from this extension though, so I expect that you should be able to use the latest version to accomplish your needs if it was working previously @Sacrilege .

**Comment by Sacrilege** [comment]
I'm referring to the categories in the In json file. You removed the build
and release category. Unfortunately since it was removed and readded I only
see version 2 as an option to choose from now.

**Comment by deadlydog** [comment]
Ahhh, you're referring to the cattegories in the `vss-extension.json`. [The docs](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#required-attributes) say that as long as you're acquiring the extension from the marketplace, it should still work for you.

> Valid values: Azure Repos, Azure Boards, Azure Pipelines, Azure Test Plans, and Azure Artifacts.
> ...
> The categories mentioned above are natively present in Visual Studio Marketplace and Azure DevOps Server 2019 & above. For extensions targeting earlier versions of Team Foundation Server (i.e. TFS <= 2018):
> 
> - If the TFS customers would be acquiring your extension via Visual Studio Marketplace (not local gallery) in connected context then leverage the categories stated above.
> - If you are going to share the extension directly (i.e. not via the Visual Studio Marketplace) with a customer using TFS <=2018 then leverage the following categories instead: Code, Plan and track, Build and release, Test, Collaborate, and Integrate. If your need is to share both via Visual Studio Marketplace and directly with a TFS <= 2018 customer then you would need to have 2 extension packages.

What is the actual issue you're encountering? The extension tasks are only available in your Build pipelines, but not in your Release pipelines?

**Comment by Sacrilege** [comment]
I haven't tried in a build pipeline as we don't have a need there. The
error I get in the release pipeline is "not valid for deploy phase" when I
try to run the existing release and when I try to add the task to another
release.

**Comment by Sacrilege** [comment]
Alright, so the problem seems to have disappeared overnight. I can still only select version 2, however, I don't get the error anymore when adding the task to a release or when running the existing one. Thanks for a quick response regardless. I really appreciate that!
