### ISSUE TITLE
Add support for Deployment Groups

### ISSUE THREAD

**Issue by mrpolaris** [deadlydog/AzureDevOps.WindowsScheduledTasks#18]
would be nice if this task worked with deployment groups

**Comment by deadlydog** [comment]
AFAIK they do work with deployment groups. I haven't set them up in the Classic Release deployment groups, but have used them in the equivalent YAML pipeline Environments, and they worked fine. What makes you think they don't work in deployment groups? Are you encountering an error?

**Comment by mrpolaris** [comment]
Sorry based on the documentation it looks like it would not work on a deployment group -  But I see you just leave the auth stuff empty.  You can close this issue
