### ISSUE TITLE
Proposal: Allow usage without specifying user account

### ISSUE THREAD

**Issue by glatzert** [deadlydog/AzureDevOps.WindowsScheduledTasks#20]
Tasks can contain a principal (especially a gMSA) which does not need a password, but may run without being logged in.
To import those tasks, the `-User` parameter must be omitted in `Register-ScheduledTask`.

I made a PR to change the `Install-WindowsScheduledTask` to accomodate for empty usernames, but I'm no "task developer" and struggle to make changes to allow empty usernames.

Also you can just call my request out-of-scope, then I'll fallback to some powershell module.

**Comment by glatzert** [comment]
#21 The "companion" PR

**Comment by deadlydog** [comment]
This is now available in v2.2.1 of the extension. Thanks so much for contributing!

**Comment by deadlydog** [comment]
The additional fix from #23 is now available in v2.3.12 of the extension. Thanks again!
